name: Build and deploy app

on:
  push:
  pull_request:
# permissions:
#   contents: write

jobs:
  build:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.1.0" # Specify the Node.js version you want to use
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      # If the app builds successfully, and is not a PR:
      # Deploy to production
      - name: Deploy with ssh
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_DEPLOY_IP }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
            source ~/.zshrc &&
            cd ~/frontend-server &&
            git reset --hard &&
            git pull &&
            npm install &&
            npm run build &&
            mkdir -p logs &&
            nohup npm run preview >> ./logs/$(date +"%Y%m%d_%H%M%S").log 2>&1 &
